[package]
name = "simurozos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scryer-prolog = { version = "0.9.4", default-features = false, features = ["hostname"] }
slint = "1.5"
